channel_sources:
- freecad/label/dev,conda-forge
channel_targets:
- astocad dev
c_stdlib_version:     # [osx]
  - '11.0'            # [osx]
c_compiler:           # [win]
  - vs2022            # [win]
cxx_compiler:         # [win]
  - vs2022            # [win]
qt6_main:
  - '6.8'
