{% set name = "astocad" %}
{% set version = "1.1" %}
{% set build_number = 118 %}
{% set build_number = build_number + 500 %}  # [FEATURE_DEBUG]

package:
    name: {{ name }}
    version: {{ version }}

source:
  - url: https://github.com/AstoCAD/FreeCAD/releases/download/weekly-builds/freecad_source.tar.gz
    fn: freecad_source_{{ build_number }}.tar.gz
    # sha256:
    patches:
        - patches/osx_arm64_cross_compiling.patch    # [build_platform != target_platform and osx]
  - path: ./branding
    folder: branding

build:
    number: {{ build_number }}
    skip: true  # [py != 311]

requirements:
    build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - qt6-main                               # [build_platform != target_platform]
        - noqt5                                  # [build_platform != target_platform]
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - cmake
        - swig
        - ninja
        - sed               # [unix]
    host:
        - coin3d
        - eigen
        - freetype
        - hdf5
        - libboost-devel
        - libegl-devel      # [linux]
        - libdrm            # [linux]
        - libgl-devel       # [linux]
        - libspnav          # [linux]
        - libxcb            # [linux]
        - matplotlib-base
        - noqt5
        - occt
        - pcl
        - pivy
        - ply
        - pybind11
        - pyside6
        - python
        - qt6-main
        - smesh
        - tbb-devel         # [win]
        - vtk
        - xerces-c
        - xorg-libxext      # [linux]
        - xorg-libxdamage   # [linux]
        - xorg-libxxf86vm   # [linux]
        - xorg-xproto       # [linux]
        - winpthreads-devel  # [win]
        - yaml-cpp
        - zlib
    run:
        - graphviz
        - gmsh
        - libspnav          # [linux]
        - numpy
        - python
        - pyside6
        - pivy
        - pyyaml
        - ply
        - requests

about:
    home: https://astocad.com/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: 'AstoCAD is a parametric 3D modeler made primarily to design real-life objects of any size. '
    description: |
        AstoCAD is a general purpose feature-based, parametric 3D modeler for
        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering
        and product design but also fits a wider range of uses in engineering,
        such as architecture or other engineering specialties. It is 100% Open
        Source (LGPL2+ license) and extremely modular, allowing for very
        advanced extension and customization.
        AstoCAD is based on FreeCAD, a free and open source project.
    doc_url: https://wiki.freecad.org/Main_Page
    dev_url: https://github.com/AstoCAD/FreeCAD

extra:
    recipe-maintainers:
        - PaddleStroke
